/**
 * Clinic & invite-code domain logic (shared between server and client).
 *
 * Pure, dependency-light helpers only — persistence lives in src/lib/db.ts
 * (Postgres) and server.ts (JSON fallback). Keeping the rules here makes the
 * invite-code flow identical in both persistence modes and directly testable.
 *
 * Model (Ecosystem Layer 1 — see docs/ideas/ecosystem-growth-loop.md):
 * - Every dentist automatically owns a personal clinic ("Dr X — Solo Practice").
 * - A clinic has one invite code. Registering with a code requests to JOIN that
 *   clinic as a PENDING member; the owner approves or declines.
 * - The code is an application credential, not a security credential: pending
 *   members see nothing until approved. Codes are rotatable if shared too widely.
 */

export type ClinicRole = 'owner' | 'dentist';
export type MembershipStatus = 'active' | 'pending';

export interface ClinicInfo {
  id: string;
  name: string;
  inviteCode: string;
  ownerDentistId: string;
}

export interface ClinicMembership {
  clinicId: string;
  clinicName: string;
  role: ClinicRole;
  status: MembershipStatus;
  /** Only exposed to the clinic owner via the API. */
  inviteCode?: string;
}

export interface ClinicMemberSummary {
  dentistId: string;
  name: string;
  role: ClinicRole;
  status: MembershipStatus;
}

/** Unambiguous alphabet — no I/L/O/1/0, so codes survive being read aloud. */
export const INVITE_ALPHABET = 'ABCDEFGHJKMNPQRSTUVWXYZ23456789';
export const INVITE_CODE_LENGTH = 6;

/**
 * Generates a random, sayable invite code, e.g. "K7T2XM".
 * Uses the Web Crypto API, which is available in browsers and Node >= 19, so
 * the same code path works on the server and in unit tests. Tests may inject
 * a deterministic `randomInt` source.
 */
export function generateInviteCode(randomInt?: (min: number, max: number) => number): string {
  const rand = randomInt ?? webRandomInt;
  let code = '';
  for (let i = 0; i < INVITE_CODE_LENGTH; i++) {
    code += INVITE_ALPHABET[rand(0, INVITE_ALPHABET.length - 1)];
  }
  return code;
}

function webRandomInt(min: number, max: number): number {
  const range = max - min + 1;
  // Rejection sampling to avoid modulo bias.
  const limit = Math.floor(0x100000000 / range) * range;
  const buf = new Uint32Array(1);
  do {
    globalThis.crypto.getRandomValues(buf);
  } while (buf[0] >= limit);
  return min + (buf[0] % range);
}

/**
 * Normalises user-typed / URL-supplied codes: trims, uppercases, strips
 * separators (people will type "abc-123" or "abc 123"). Returns null when the
 * result cannot be a valid code.
 */
export function normalizeInviteCode(raw: unknown): string | null {
  if (typeof raw !== 'string') return null;
  const cleaned = raw.trim().toUpperCase().replace(/[^A-Z0-9]/g, '');
  if (cleaned.length < 4 || cleaned.length > 12) return null;
  return cleaned;
}

/** Strict check for codes generated by generateInviteCode (6 chars, safe alphabet). */
export function isGeneratedInviteCode(code: string): boolean {
  return new RegExp(`^[${INVITE_ALPHABET}]{${INVITE_CODE_LENGTH}}$`).test(code);
}

/**
 * Sanitizes a clinic name: collapses whitespace, strips angle brackets, caps
 * length. Returns null when nothing usable remains.
 */
export function sanitizeClinicName(raw: unknown): string | null {
  if (typeof raw !== 'string') return null;
  const cleaned = raw.replace(/[<>]/g, '').replace(/\s+/g, ' ').trim();
  if (cleaned.length < 2 || cleaned.length > 80) return null;
  return cleaned;
}

/** Default display name for the automatic personal clinic of a dentist. */
export function personalClinicName(dentistName: string): string {
  const base = dentistName.replace(/[<>]/g, '').replace(/\s+/g, ' ').trim() || 'My';
  return `${base} — Solo Practice`.slice(0, 80);
}
