import type { AppointmentType } from './lib/dentalLibrary';

export type { AppointmentType };

export interface TranscriptItem {
  sender: 'Dentist' | 'Patient' | 'Dialogue' | 'Clinical Comment';
  text: string;
}

export interface AdaCodeItem {
  code: string;
  description: string;
  tooth?: string;
}

export interface ClinicalFindings {
  chiefComplaint: string;
  history: string;
  toothFindings: string;
  findingsGingival: string;
  diagnosis: string;
  treatmentPerformed: string;
  recommendations: string;
  recallRequirements: string;
  customSections?: Record<string, string>;
  adaCodes?: AdaCodeItem[];
}

/** How the note content in this record was produced — surfaced transparently in the UI. */
export interface NoteOrigin {
  engine: 'gemini' | 'offline-draft' | 'on-device';
  /** True when the content was auto-generated by a fallback path and needs clinician review. */
  needsReview: boolean;
  /** Short human note, e.g. 'Generated while Gemini quota was exhausted'. */
  detail?: string;
}

/**
 * Engine-agnostic note payload produced by every note source (hosted Gemini,
 * secondary key, offline draft engine, on-device WebLLM). `canonical` holds
 * the eight standard clinical fields; `customSections` holds any additional
 * template-specific sections.
 */
export interface GeneratedNotePayload {
  engine?: 'gemini' | 'offline-draft' | 'on-device';
  modelId?: string;
  canonical: Record<string, string>;
  customSections: Record<string, string>;
  patientSummary: string;
  adaCodes: AdaCodeItem[];
}

export interface Consultation {
  id: string;
  dentistId?: string;
  firstName: string;
  lastName: string;
  dob: string;
  appointmentType: AppointmentType;
  date: string; // e.g., 'Oct 24'
  time: string; // e.g., '09:45 AM'
  status: 'Completed' | 'In Review';
  transcript: TranscriptItem[];
  findings: ClinicalFindings;
  patientSummary: string;
  templateId?: string;
  noteOrigin?: NoteOrigin;
}

export const getTodayStr = () => {
  const dateObj = new Date();
  const months = ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'];
  return `${months[dateObj.getMonth()]} ${dateObj.getDate()}`;
};

export const getYesterdayStr = () => {
  const dateObj = new Date();
  dateObj.setDate(dateObj.getDate() - 1);
  const months = ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'];
  return `${months[dateObj.getMonth()]} ${dateObj.getDate()}`;
};

export const getCurrentTimeStr = () => {
  const dateObj = new Date();
  const minutes = dateObj.getMinutes().toString().padStart(2, '0');
  let hours = dateObj.getHours();
  const ampm = hours >= 12 ? 'PM' : 'AM';
  hours = hours % 12 || 12;
  return `${hours.toString().padStart(2, '0')}:${minutes} ${ampm}`;
};
