import type { AppointmentType } from './lib/dentalLibrary';

export type { AppointmentType };

export interface TranscriptItem {
  sender: 'Dentist' | 'Patient' | 'Dialogue' | 'Clinical Comment';
  text: string;
}

export interface AdaCodeItem {
  code: string;
  description: string;
  tooth?: string;
}

export interface ClinicalFindings {
  chiefComplaint: string;
  history: string;
  toothFindings: string;
  findingsGingival: string;
  diagnosis: string;
  treatmentPerformed: string;
  recommendations: string;
  recallRequirements: string;
  customSections?: Record<string, string>;
  adaCodes?: AdaCodeItem[];
}

/** How the note content in this record was produced — surfaced transparently in the UI. */
export interface NoteOrigin {
  engine: 'gemini' | 'offline-draft' | 'on-device';
  /** True when the content was auto-generated by a fallback path and needs clinician review. */
  needsReview: boolean;
  /** Short human note, e.g. 'Generated while Gemini quota was exhausted'. */
  detail?: string;
  /** Model/engine identifier that produced the content (audit provenance). */
  modelId?: string;
  /** When generation happened (ISO). */
  generatedAt?: string;
  /** Disclosure version the patient was shown when this content was captured. */
  disclosureVersion?: string;
}

/**
 * Patient consent to AI-assisted charting, captured before a recording starts.
 * Stored with the consultation so the clinic can evidence what the patient was
 * told and when (APP 3/5 — see the in-app notice in src/components/LegalPage.tsx
 * and docs/legal/data-flow-and-subprocessors.md).
 */
export interface ConsultationConsent {
  /** ISO timestamp of the verbal consent. */
  obtainedAt: string;
  /** Which disclosure wording was used (src/lib/compliance.ts). */
  disclosureVersion: string;
  /** Who recorded it. */
  recordedBy: string;
}

/**
 * One saved revision of a consultation. Clinical records are append-only in
 * intent: the current state is the consultation body, and every save appends
 * who changed it and when, so an edit can never silently rewrite history.
 */
export interface ConsultationRevision {
  id: string;
  savedAt: string;
  savedBy: string;
  engine?: NoteOrigin['engine'];
  /** True when this revision was written by the async AI worker. */
  systemGenerated?: boolean;
}

/**
 * Engine-agnostic note payload produced by every note source (hosted Gemini,
 * secondary key, offline draft engine, on-device WebLLM). `canonical` holds
 * the eight standard clinical fields; `customSections` holds any additional
 * template-specific sections.
 */
export interface GeneratedNotePayload {
  engine?: 'gemini' | 'offline-draft' | 'on-device';
  modelId?: string;
  canonical: Record<string, string>;
  customSections: Record<string, string>;
  patientSummary: string;
  adaCodes: AdaCodeItem[];
}

export interface Consultation {
  id: string;
  dentistId?: string;
  /** Clinic this consultation was recorded in (stamped server-side). */
  clinicId?: string;
  firstName: string;
  lastName: string;
  dob: string;
  appointmentType: AppointmentType;
  date: string; // e.g., 'Oct 24'
  time: string; // e.g., '09:45 AM'
  status: 'Completed' | 'In Review';
  transcript: TranscriptItem[];
  findings: ClinicalFindings;
  patientSummary: string;
  templateId?: string;
  noteOrigin?: NoteOrigin;
  /** AI-assist consent captured at intake (required for new records). */
  consent?: ConsultationConsent;
  /** Append-only revision trail (server-maintained). */
  revisions?: ConsultationRevision[];
}

export const getTodayStr = (when: Date = new Date()) => {
  const months = ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'];
  return `${months[when.getMonth()]} ${when.getDate()}`;
};

export const getYesterdayStr = () => {
  const dateObj = new Date();
  dateObj.setDate(dateObj.getDate() - 1);
  const months = ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'];
  return `${months[dateObj.getMonth()]} ${dateObj.getDate()}`;
};

export const getCurrentTimeStr = (when: Date = new Date()) => {
  const minutes = when.getMinutes().toString().padStart(2, '0');
  let hours = when.getHours();
  const ampm = hours >= 12 ? 'PM' : 'AM';
  hours = hours % 12 || 12;
  return `${hours.toString().padStart(2, '0')}:${minutes} ${ampm}`;
};
