import type { AppointmentType } from './lib/dentalLibrary';

export type { AppointmentType };

export interface TranscriptItem {
  sender: 'Dentist' | 'Patient' | 'Dialogue' | 'Clinical Comment';
  text: string;
}

export interface AdaCodeItem {
  code: string;
  description: string;
  tooth?: string;
}

export type TreatmentStatus = 'unscheduled' | 'contacted' | 'booked' | 'completed' | 'declined';

export type PmsType = 'cliniko' | 'corepractice' | 'd4w' | 'exact' | 'dentrix' | 'other';

export interface TreatmentOpportunity {
  id: string;
  consultationId: string;
  dentistId: string;
  clinicId?: string;
  patientName: string;
  patientPhone?: string;
  patientEmail?: string;
  tooth?: string; // FDI notation e.g. "16"
  surfaces?: string; // e.g. "MOD"
  adaCode: string; // e.g. "611"
  procedureName: string; // e.g. "Full Crown - Ceramic"
  estimatedFee: number; // e.g. 1650
  clinicalReason: string;
  patientBarrier?: string;
  status: TreatmentStatus;
  lastContactedAt?: string;
  bookedAt?: string;
  createdAt: string;
  // Closed-loop PMS verification fields
  pmsType?: PmsType;
  pmsAppointmentId?: string;
  pmsBookingRef?: string;
  pmsSyncStatus?: 'unlinked' | 'verified' | 'auto_synced';
}

export interface PracticeRoiSummary {
  clinicId: string;
  month: string;
  totalIdentifiedValue: number;
  totalBookedValue: number;
  totalCompletedValue: number;
  unscheduledCount: number;
  bookedCount: number;
  declinedCount?: number;
  declinedValue?: number;
  subscriptionCost: number;
  netRoiMultiple: number;
  // Closed-loop verified metrics
  verifiedBookedValue?: number;
  verifiedBookedCount?: number;
  conversionRatePct?: number;
  averageDaysToBook?: number;
}

export interface SpecialistReferral {
  required: boolean;
  specialty?: 'Endodontics' | 'Periodontics' | 'Oral & Maxillofacial Surgery' | 'Orthodontics' | 'Prosthodontics' | 'Paediatric Dentistry' | 'General Referral';
  specialistName?: string;
  recipientClinic?: string;
  teethInvolved?: string[]; // FDI notation e.g. ["16"]
  urgency?: 'Routine' | 'Urgent' | 'Immediate (Emergency)';
  clinicalQuestion: string; // e.g. "Assessment and root canal therapy for tooth 16"
  backgroundAndFindings: string; // concise clinical summary, pulp vitality, radiographic signs
  provisionalDiagnosis: string;
  interimTreatmentProvided?: string; // e.g. "Pulp extirpation under rubber dam, ledermix dressing placed"
  medicalAlerts?: string;
  letterText: string; // ready-to-send formal referral letter
}

export interface PatientConsentOption {
  optionName: string;
  benefits: string;
  risks: string;
  estimatedCost?: string;
}

export interface PatientConsentAndCare {
  plainSummary: string;
  optionsDiscussed: PatientConsentOption[];
  risksOfNoTreatment: string;
  postOpCareInstructions: string;
  redFlagsWarning: string;
  consentStatus?: 'discussed_pending_signature' | 'verbally_consented' | 'written_consent_signed';
}

export interface TreatmentQuoteItem {
  adaCode: string;
  description: string;
  tooth?: string;
  fee: number;
  healthFundEstimatedRebate: number;
  gapEstimate: number;
  category: 'Diagnostic' | 'Preventive' | 'Periodontics' | 'Endodontics' | 'Restorative' | 'Crown & Bridge' | 'Surgery' | 'Orthodontics';
}

export interface TreatmentQuoteData {
  items: TreatmentQuoteItem[];
  totalFee: number;
  estimatedRebate: number;
  netGap: number;
  visualCaseCategory?: 'crown' | 'implant' | 'endo' | 'veneer' | 'aligner' | 'perio' | 'general';
  phasedMilestones?: Array<{
    phaseNumber: number;
    phaseTitle: string;
    items: string[];
    totalPhaseFee: number;
  }>;
}

export interface ClinicalFindings {
  chiefComplaint: string;
  history: string;
  toothFindings: string;
  findingsGingival: string;
  diagnosis: string;
  treatmentPerformed: string;
  recommendations: string;
  recallRequirements: string;
  customSections?: Record<string, string>;
  adaCodes?: AdaCodeItem[];
  proposedTreatments?: TreatmentOpportunity[];
}

/** How the note content in this record was produced — surfaced transparently in the UI. */
export interface NoteOrigin {
  engine: 'gemini' | 'offline-draft' | 'on-device';
  /** True when the content was auto-generated by a fallback path and needs clinician review. */
  needsReview: boolean;
  /** Short human note, e.g. 'Generated while Gemini quota was exhausted'. */
  detail?: string;
}

/**
 * Engine-agnostic note payload produced by every note source (hosted Gemini,
 * secondary key, offline draft engine, on-device WebLLM). `canonical` holds
 * the eight standard clinical fields; `customSections` holds any additional
 * template-specific sections.
 */
export interface GeneratedNotePayload {
  engine?: 'gemini' | 'offline-draft' | 'on-device';
  modelId?: string;
  canonical: Record<string, string>;
  customSections: Record<string, string>;
  patientSummary: string;
  adaCodes: AdaCodeItem[];
  proposedTreatments?: TreatmentOpportunity[];
  specialistReferral?: SpecialistReferral;
  patientConsent?: PatientConsentAndCare;
  treatmentQuote?: TreatmentQuoteData;
}

export interface Consultation {
  id: string;
  dentistId?: string;
  /** Clinic this consultation was recorded in (stamped server-side). */
  clinicId?: string;
  firstName: string;
  lastName: string;
  dob: string;
  appointmentType: AppointmentType;
  date: string; // e.g., 'Oct 24'
  time: string; // e.g., '09:45 AM'
  status: 'Completed' | 'In Review';
  transcript: TranscriptItem[];
  findings: ClinicalFindings;
  patientSummary: string;
  templateId?: string;
  noteOrigin?: NoteOrigin;
  proposedTreatments?: TreatmentOpportunity[];
  specialistReferral?: SpecialistReferral;
  patientConsent?: PatientConsentAndCare;
  treatmentQuote?: TreatmentQuoteData;
}

export const getTodayStr = (when: Date = new Date()) => {
  const months = ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'];
  return `${months[when.getMonth()]} ${when.getDate()}`;
};

export const getYesterdayStr = () => {
  const dateObj = new Date();
  dateObj.setDate(dateObj.getDate() - 1);
  const months = ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'];
  return `${months[dateObj.getMonth()]} ${dateObj.getDate()}`;
};

export const getCurrentTimeStr = (when: Date = new Date()) => {
  const minutes = when.getMinutes().toString().padStart(2, '0');
  let hours = when.getHours();
  const ampm = hours >= 12 ? 'PM' : 'AM';
  hours = hours % 12 || 12;
  return `${hours.toString().padStart(2, '0')}:${minutes} ${ampm}`;
};
